Back Button
UTM-Hacklab/utmhacklab.tech pull request #36
Opened 2020-02-29 22:15 UTC by itsninaricci29

created a back button on the Show Landing page that redirects the user to home page

2020-03-01 17:54 UTC, ArsalaBangash requested changes
### Great work! 

**Please add .idea to the gitignore file, so the Webstorm config files are ignored.**

I changed the back button to only be visible at the top of the page. You can view the changes between my commit and yours [here](https://github.com/UTM-Hacklab/utmhacklab.tech/pull/36/commits/6109266c88bfb93ef3d5be1a2f508cda0c49c310) to see how I did it.

2020-03-01 23:03 UTC, itsninaricci29 commented
Pushed the change for the gitignore.

2020-03-02 01:21 UTC, ArsalaBangash requested changes
You added correctly to the gitignore, but the .idea content was still in the git index. You have to run 
```git rm -rf .idea``` 
to get rid of the files from the index.

2020-03-02 01:32 UTC, ArsalaBangash approved these changes

2020-03-02 01:32 UTC, merged